In [1]:
# Limitations of ANN (Image Data):
# 1. Image ke spatial relationships ko preserve nahi karta.
# 2. Har pixel ko alag feature maanta hai, isliye image structure lose ho jata hai.
# 3. Bahut zyada parameters hote hain, jiski wajah se training slow hoti hai.
# 4. Memory aur computation ki requirement bahut high hoti hai.
# 5. Overfitting ka chance zyada hota hai, especially large images par.
# 6. Features (edges, shapes, textures) automatically detect nahi kar pata.
# 7. Image recognition tasks me accuracy CNN se kam hoti hai.

# Isi limitations ko solve karne ke liye CNN introduce kiya gaya,
# jo filters ki help se important image features efficiently learn karta hai.

# Spatial ka matlab hota hai image me pixels ki position aur unke aas-paas ke pixels ke saath relation.
# Example: Agar kisi image me eye nose ke upar hai aur mouth nose ke neeche,
# to ye unki spatial relationship hai.
# CNN is relationship ko preserve karta hai, isliye image ko better samajh pata hai.
# ANN image ko sirf numbers ki list bana deta hai, jisse ye relation lose ho jata hai.

# CNN use karte hain kyunki image ke nearby pixels ek dusre se related hote hain.
# CNN filters ki help se image ke patterns (edges, shapes, features) easily learn karta hai.
# ANN har pixel ko alag feature maanta hai, isliye image ke liye efficient nahi hota.

In [2]:
# Working of CNN:
# 1. Input Layer: Image ko pixel values ke form me CNN me diya jata hai.
# 2. Convolution Layer: Filters (kernels) image par slide hote hain aur
#    edges, lines, textures aur important features detect karte hain.
# 3. ReLU Activation: Negative values ko 0 aur positive values ko same rakhta hai,
#    jisse model complex patterns bhi learn kar pata hai.
# 4. Pooling Layer: Feature map ka size reduce karta hai aur sirf important
#    information ko retain karta hai, jisse computation kam hoti hai.
# 5. Flatten Layer: 2D feature maps ko 1D vector me convert karta hai.
# 6. Fully Connected Layer: Extracted features ko use karke classes ke
#    probabilities calculate karta hai.
# 7. Output Layer: Sabse high probability wali class ko final prediction ke
#    roop me return karta hai.

In [3]:
# Kernel (Filter) in CNN:
# Kernel ek chhota matrix hota hai (jaise 3x3 ya 5x5) jo image par slide karta hai.
# Iska kaam image ke important features jaise edges, corners, textures aur patterns
# ko detect karna hota hai.

# Kaise kaam karta hai?
# 1. Kernel image ke ek chhote region par place hota hai.
# 2. Har pixel ko kernel ki corresponding value se multiply kiya jata hai.
# 3. Sab multiplication ka sum nikala jata hai.
# 4. Ye value output feature map me store hoti hai.
# 5. Phir kernel ek step aage (stride) move karta hai aur process repeat hota hai.

# Example (3x3 Kernel):
# Image Patch          Kernel
# [2 3 1]              [ 1  0 -1]
# [4 5 2]      ×       [ 1  0 -1]
# [6 7 3]              [ 1  0 -1]

# Har position par convolution perform karke ek Feature Map banti hai.

# Important Points:
# - Ek image par multiple kernels use hote hain.
# - Har kernel alag feature learn karta hai.
# - Initial layers edges aur lines detect karti hain.
# - Deep layers complex features jaise eyes, face, car, etc. detect karti hain.
# - Kernel ki values training ke time automatically learn hoti hain.

In [4]:
# ======================== WORKING OF CNN ========================

# CNN (Convolutional Neural Network) image se important features
# (edges, textures, shapes, objects) automatically detect karta hai
# aur unke basis par final prediction karta hai.

# CNN Flow:
# Input Image → Convolution → ReLU → Pooling → Flatten
# → Fully Connected Layer → Output

# ---------------------------------------------------------------
# Step 1: Input Image (4x4)
#
# [1 2 3 4]
# [5 6 7 8]
# [9 1 2 3]
# [4 5 6 7]
#
# Har number image ke ek pixel ki intensity ko represent karta hai.

# ---------------------------------------------------------------
# Step 2: Convolution Layer
#
# Convolution me ek chhota matrix (Kernel/Filter) image par slide karta hai
# aur important features detect karta hai.
#
# Kernel (2x2)
#
# [1 0]
# [0 1]
#
# Stride = 1 (Kernel har baar 1 pixel move karega)
# Padding = 0 (Image ke bahar koi extra zeros nahi hain)

# First Position
#
# Image Patch
#
# [1 2]
# [5 6]
#
# Calculation
#
# (1×1)+(2×0)+(5×0)+(6×1)
# =1+0+0+6
# =7
#
# First Output = 7

# Kernel ab ek pixel right move karega.

# Second Patch
#
# [2 3]
# [6 7]
#
# (2×1)+(3×0)+(6×0)+(7×1)
# =9

# Isi tarah pura image process hota hai.

# Final Feature Map
#
# [ 7  9 11]
# [ 6  8 10]
# [14  7  9]
#
# 4×4 image → 3×3 feature map ban gayi.

# ---------------------------------------------------------------
# Step 3: Stride
#
# Stride batata hai kernel ek baar me kitne pixels move karega.
#
# Stride = 1 → Har baar 1 pixel move
# Stride = 2 → Har baar 2 pixels jump
#
# Bada stride:
# ✔ Faster computation
# ✔ Chhota output
# ✖ Kuch information miss ho sakti hai.

# ---------------------------------------------------------------
# Step 4: Padding
#
# Padding ka matlab image ke border ke around extra zeros add karna.
#
# Original
# [1 2]
# [3 4]
#
# After Padding
#
# [0 0 0 0]
# [0 1 2 0]
# [0 3 4 0]
# [0 0 0 0]
#
# Padding edge pixels ki information preserve karta hai
# aur output size ko control karta hai.

# ---------------------------------------------------------------
# Step 5: ReLU Activation
#
# ReLU (Rectified Linear Unit)
#
# Formula:
# f(x) = max(0,x)
#
# Example
#
# Before
# [-3 4]
# [ 5 -2]
#
# After ReLU
# [0 4]
# [5 0]
#
# Negative values ko 0 aur positive values ko same rakhta hai.
# Isse model complex patterns learn kar pata hai.

# ---------------------------------------------------------------
# Step 6: Max Pooling
#
# Pooling feature map ka size reduce karta hai
# aur sirf important information retain karta hai.
#
# Example (2×2 Max Pooling)
#
# [7 9]
# [6 8]
#
# Maximum = 9
#
# Output
# [9]
#
# Benefits:
# ✔ Size reduce hota hai
# ✔ Computation kam hoti hai
# ✔ Overfitting reduce hoti hai

# ---------------------------------------------------------------
# Step 7: Flatten
#
# Feature Map
#
# [9 11]
# [14 10]
#
# Flatten
#
# [9, 11, 14, 10]
#
# 2D data ko 1D vector me convert karta hai.

# ---------------------------------------------------------------
# Step 8: Fully Connected Layer
#
# Flattened features Dense (ANN) layer me jate hain.
# Ye extracted features ke basis par prediction karta hai.

# ---------------------------------------------------------------
# Step 9: Output Layer
#
# Example
#
# Cat  : 96%
# Dog  : 3%
# Bird : 1%
#
# Final Prediction = Cat

# ======================== SUMMARY ========================
#
# Input Image
#      ↓
# Convolution (Kernel)
#      ↓
# Feature Map
#      ↓
# ReLU
#      ↓
# Max Pooling
#      ↓
# Flatten
#      ↓
# Fully Connected Layer
#      ↓
# Output Prediction

In [13]:
#CNN on MNIST dataset

# ===================== IMPORTING LIBRARIES =====================

# TensorFlow deep learning aur neural networks banane ke liye use hota hai.
import tensorflow as tf

# MNIST dataset (0–9 handwritten digit images) load karne ke liye.
from tensorflow.keras.datasets import mnist

# Labels (0–9) ko One-Hot Encoding format me convert karne ke liye.
# Example: 3 → [0,0,0,1,0,0,0,0,0,0]
from tensorflow.keras.utils import to_categorical

# Sequential model banane ke liye, jisme layers ek ke baad ek add hoti hain.
from tensorflow.keras.models import Sequential

# Conv2D      : Convolution layer, image se edges, textures aur features detect karti hai.
# MaxPooling2D: Feature map ka size reduce karti hai aur important information retain karti hai.
# Flatten     : 2D feature maps ko 1D vector me convert karta hai.
# Dense       : Fully Connected (ANN) layer, final prediction/classification karti hai.
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# NumPy numerical operations aur arrays handle karne ke liye.
import numpy as np

In [14]:
# ===================== LOAD DATA =====================

# MNIST dataset load kar rahe hain.
# x_train, x_test -> Images
# y_train, y_test -> Labels (0–9)
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# ===================== PRE-PROCESSING =====================

# Images ko reshape kar rahe hain.
# -1 = Number of images automatically calculate ho jayega.
# 28x28 = Image size
# 1 = Grayscale image ka ek color channel
# /255.0 = Pixel values (0–255) ko 0–1 range me normalize karta hai.
x_train = x_train.reshape(-1, 28, 28, 1) / 255.0
x_test = x_test.reshape(-1, 28, 28, 1) / 255.0

# Labels ko One-Hot Encoding me convert kar rahe hain.
# Example: 5 → [0,0,0,0,0,1,0,0,0,0]
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [15]:
#CNN Model

# ===================== CNN MODEL =====================

# Sequential model create kar rahe hain, jisme layers ek ke baad ek execute hongi.
model = Sequential([

    # Conv2D Layer
    # 32 = Number of filters (32 different features learn honge)
    # (3,3) = Kernel size (3x3 filter)
    # ReLU = Negative values ko 0 aur positive values ko same rakhta hai.
    # input_shape = 28x28 grayscale image (1 channel)
    Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),

    # Max Pooling Layer
    # (2,2) window se maximum value select karta hai.
    # Feature map ka size reduce karta hai aur computation kam karta hai.
    MaxPooling2D((2,2)),

    # Flatten Layer
    # 2D feature maps ko 1D vector me convert karta hai
    # taaki Dense layer input le sake.
    Flatten(),

    # Hidden Dense Layer
    # 128 neurons extracted features ko process karte hain.
    # ReLU complex patterns learn karne me help karta hai.
    Dense(128, activation='relu'),

    # Output Layer
    # 10 neurons = Digits 0–9 ke liye.
    # Softmax har class ki probability deta hai.
    # Jiski probability sabse zyada hogi wahi final prediction hoga.
    Dense(10, activation='softmax')
])

C:\Users\Prateek Verma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [17]:
# ===================== COMPILE MODEL =====================

# Model ko training ke liye configure kar rahe hain.
model.compile(

    # Adam optimizer training ke time weights update karta hai
    # taaki loss kam ho aur model better learn kare.
    optimizer='adam',

    # One-Hot Encoded labels ke liye loss function.
    loss='categorical_crossentropy',

    # Har epoch ke baad model ki accuracy calculate karega.
    metrics=['accuracy']
)

# ===================== TRAIN MODEL =====================

# Model ko training data par train kar rahe hain.
model.fit(

    # Training images
    x_train,

    # Training labels
    y_train,

    # Validation data:
    # Har epoch complete hone ke baad model is data par test hota hai.
    # Is data se weights update nahi hote, sirf performance evaluate hoti hai.
    validation_data=(x_test, y_test),

    # Epochs:
    # 1 Epoch = Model poore training dataset ko ek baar complete dekhta hai.
    # epochs=3 matlab model training data ko 3 baar dekhega.
    epochs=3
)

Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 26s 13ms/step - accuracy: 0.9928 - loss: 0.0224 - val_accuracy: 0.9869 - val_loss: 0.0416
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 43s 14ms/step - accuracy: 0.9953 - loss: 0.0151 - val_accuracy: 0.9880 - val_loss: 0.0416
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 27s 14ms/step - accuracy: 0.9970 - loss: 0.0092 - val_accuracy: 0.9854 - val_loss: 0.0477


In [19]:
# ===================== SAVE MODEL =====================

# Trained model ko Keras format (.keras) me save kar rahe hain.
# Isme model architecture, learned weights aur training information save hoti hai.
# Baad me bina dobara training ke model ko directly load karke use kar sakte hain.
model.save("mnist_cnn.keras")